version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/app
  
  frontend:
    build: ./Frontend
    ports:
      - 3000:3000
    volumes:
      - ./Frontend:/app